baseURL = 'https://andyzzzzzzzzz.github.io/'
locale = 'en-US'
title = 'Kunpeng Zhang'
theme = 'blowfish'

defaultContentLanguage = 'en'
enableRobotsTXT = true
summaryLength = 0
enableEmoji = true

[pagination]
  pagerSize = 100

[taxonomies]
  tag = 'tags'
  category = 'categories'
  author = 'authors'
  series = 'series'

[outputs]
  home = ['HTML', 'RSS', 'JSON']
