baseURL = 'https://andyzzzzzzzzz.github.io/'
locale = 'en-US'
title = 'Kunpeng Zhang'
theme = 'blowfish'

defaultContentLanguage = 'en'
enableRobotsTXT = true
summaryLength = 0
enableEmoji = true
disableKinds = ['taxonomy', 'term']

[pagination]
  pagerSize = 100

[outputs]
  home = ['HTML', 'RSS', 'JSON']
